### ISSUE TITLE
Exception on creating a specialized collector

### ISSUE THREAD

**Issue by sidhoda** [nblumhardt/influxdb-lineprotocol#3]
Calling the following:

Metrics.Specialize().CreateCollector()

Will result in an ArgumentException with message:
"Parent may not be specified here"

As far as I can the assertion on parent being null in PipelinedCollectorEmitConfiguration.CreateEmitter makes Specialize unusable as it would always be raised.

**Comment by sidhoda** [comment]
Just to confirm, is the intention of this method to be similar to ILogger.ForContext in Serilog? 

That's more or less how I'm trying to use it, applying some additional tags to a specific portion of code.

**Comment by nblumhardt** [comment]
Thanks Sid, appreciate the report - fixed now.

Yes, that's the intention - specializing an emitter will allow different tags to be added to the emitted points.

Still a lot to do in this library, the design is still coming together. Any and all help welcome :-)

**Comment by sidhoda** [comment]
Great! Thanks for the quick fix.
