### ISSUE TITLE
Missing a way to send the timestamp

### ISSUE THREAD

**Issue by HakanL** [nblumhardt/influxdb-lineprotocol#7]
Sometimes it's good to be able to send a timestamp with the measurement if it's coming off an offline queue.

**Comment by nblumhardt** [comment]
Thanks for the note! The "raw client" should cover off this scenario, e.g. the first example in [Raw Client](https://github.com/nblumhardt/influxdb-lineprotocol#raw-client-api) shows the timestamp being passed explicitly. Does this cover what you need?

Regards,
Nick

**Comment by HakanL** [comment]
Right, but I liked the batch process and was planning to use that. An
overload would be good for the main client :)

**Comment by nblumhardt** [comment]
Resolved by #7.

**Comment by maxisam** [comment]
is it possible to add this overload to here as well
https://github.com/influxdata/influxdb-csharp/blob/dev/src/InfluxDB.Collector/Metrics.cs

So we don't need to call Metrics.Collector.Write.
